server.port=8085
spring.application.name=notification-service

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.rabbitmq.listener.simple.acknowledge-mode=manual

sendgrid.api.key=${SENDGRID_API_KEY:your_sendgrid_key}
sendgrid.from.email=${SENDGRID_FROM_EMAIL:}

spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER:}
spring.mail.password=${SMTP_PASSWORD:}

participant.service.url=http://localhost:8083/api/participants
