server.port=8083
spring.application.name=participant-service

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/cert_sender_db}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
